---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: CHANGEME
  namespace: CHANGEME
  labels:
    app: CHANGEME 
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: CHANGEME
  template:
    metadata:
      labels:
        app: CHANGEME
    spec:
      automountServiceAccountToken: false
      volumes:
      - name: CHANGEME-persistent-storage
        persistentVolumeClaim:
          claimName: CHANGEME-pvc-claim
      - name: appdbmnt
        emptyDir: {}
      - name: textmount
        emptyDir: {}
      - name: tmpmount
        emptyDir: {}
      - name: genroutes
        emptyDir: {}
      - name: CHANGEME-creds-volume
        secret:
          secretName: CHANGEME-envvars-secret
      containers:
      - image: ghcr.io/CHANGEME/CHANGEME/automation-portal-CHANGEME:3.2.1
        name: CHANGEME
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: CHANGEME-persistent-storage
          mountPath: /opt/pvc/
          readOnly: false
        - name: appdbmnt
          mountPath: /usr/portal/appdatabase
          readOnly: false
        - name: genroutes
          mountPath: /usr/portal/genroutes
          readOnly: false
        - name: textmount
          mountPath: /usr/portal/supporting_tools/textfiles/
          readOnly: false
        - name: tmpmount
          mountPath: /tmp
          readOnly: false
        - name: CHANGEME-creds-volume
          mountPath: /usr/portal/envvars.sh
          subPath: envvars.sh
          readOnly: true
        securityContext:
          readOnlyRootFilesystem: true
#          seccompProfile:
#            type: RuntimeDefault
          allowPrivilegeEscalation: false
          runAsUser: 15000
        readinessProbe:
           exec:
              command:
              - /bin/sh
              - /usr/portal/healthcheck.sh
           initialDelaySeconds: 45
           periodSeconds: 60
           timeoutSeconds: 30
           failureThreshold: 2
        livenessProbe:
           exec:
              command:
              - /bin/sh
              - /usr/portal/healthcheck.sh
           initialDelaySeconds: 60
           periodSeconds: 300
           timeoutSeconds: 30
           failureThreshold: 4
        env:
          - name: COMPANY_K8S_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: PYTHONUNBUFFERED
            value: '1'
          - name: SERVER_NAME
            value: CHANGEME.CHANGEME
          - name: SNOW_HOST
            value: 'https://CHANGEME.service-now.com/'
          - name: SESSION_COOKIE_NAME
            value: 'csrfsession'
          - name: WEBSITE_URL
            value: 'https://CHANGEME-np.CHANGEME'
          - name: CHANGEMEPI_URL
            value: 'CHANGEME-staging.CHANGEME'
          - name: AUTOMATE_ENVIRONMENT
            value: "non-production"
          - name: LDAP_HOST
            value: 'CHANGEME.CHANGEME'
          - name: CERT_VERIFY
            value: '/etc/ssl/certs/ca-certificates.crt'
          - name: LDAP_BASEDN
            value: 'OU=CHANGEME,DC=CHANGEME,DC=CHANGEME,DC=com'
          # comma-separated string of disabled endpoint names (not awx job names)
          - name: DISABLED_ENDPOINTS
            value: ""
          # comma-separated string of disabled awx job names (for compatibility with awxjobrunconf)
          - name: DISABLED_AWX_JOBS
            value: ""
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "384Mi"
            cpu: "200m"
      restartPolicy: Always
