#!/bin/sh
cd /usr/portal/
/usr/sbin/crond 
python3 createroutesfromjson.py > /usr/portal/autogeneratedroutes.py
python3 grab_snow_apps.py /usr/portal/supporting_tools/textfiles/snowapps.txt
gunicorn -w 4 -b 0.0.0.0:8000 wsgi:app
